version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: steel
      POSTGRES_PASSWORD: steel
      POSTGRES_DB: steel
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://steel:steel@postgres:5432/steel
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api:3000
    ports:
      - "3001:3001"
    depends_on:
      - api

volumes:
  postgres_data:
